# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov codecov
  - pip install numpy
  - pip install codecov
  - pip install tensorflow
  - pip install theano
  - pip install dask[array]
  - pip install sparse
  - pip install -e .
  - if [ `python -c "import numpy; print(numpy.version.version)"` == "1.14.0" ]; then
        pip install numpy --upgrade;
    fi

script:
  - py.test -v --cov=./

# after_success:
#   - ./tools/travis-upload-wheel.sh

notifications:
    email: false

after_success:
  - codecov
